name: playwright

on:
  pull_request:
  push:
    branches: [master]
    paths:
      - 'packages/motion/**'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Run a build step here
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i --no-frozen-lockfile
      
      - name: Build Motion
        run: pnpm build

      - name: Install playwright browsers
        run: npx playwright install --with-deps
        
      - name: Run tests
        run: pnpm test:e2e
